name: MinecartNoEscape
version: alpha-0.3
main: net.corecrafted.mcne.McneMain
description: A small plugin to get rid of player escaping from minecraft while in tutorial tracks
author: ThisTNTSquid
commands:
  mcne:
    description: Minecart No Escape main command
    usage: /mcne <lock/unlock> <player/-near>
permissions:
  mcne.control:
    description: permission to control minecart locking function
    default: op